pipeline{
    agent any
    stages{
        stage("git check out"){
            steps{
                git branch :'jenkins', url
            }
        }
        stage("build"){
            steps{
                sh 'shell.sh'
                sh 'chmod 777 shell.sh'
            }
        }
    }
}